export type CountryCode = {
  code: string      // 国家代码 (如 "CN", "US")
  name: string      // 国家名称 (如 "中国", "美国")
  dialCode: string  // 国际拨号代码 (如 "+86", "+1")
  flag: string      // 国旗emoji (如 "🇨🇳", "🇺🇸")
}

export const countryCodes: CountryCode[] = [
  { code: "CN", name: "中国", dialCode: "+86", flag: "🇨🇳" },
  { code: "US", name: "美国", dialCode: "+1", flag: "🇺🇸" },
  { code: "JP", name: "日本", dialCode: "+81", flag: "🇯🇵" },
  { code: "KR", name: "韩国", dialCode: "+82", flag: "🇰🇷" },
  { code: "SG", name: "新加坡", dialCode: "+65", flag: "🇸🇬" },
  { code: "HK", name: "香港", dialCode: "+852", flag: "🇭🇰" },
  { code: "TW", name: "台湾", dialCode: "+886", flag: "🇹🇼" },
  { code: "GB", name: "英国", dialCode: "+44", flag: "🇬🇧" },
  { code: "DE", name: "德国", dialCode: "+49", flag: "🇩🇪" },
  { code: "FR", name: "法国", dialCode: "+33", flag: "🇫🇷" },
  { code: "CA", name: "加拿大", dialCode: "+1", flag: "🇨🇦" },
  { code: "AU", name: "澳大利亚", dialCode: "+61", flag: "🇦🇺" },
  { code: "NZ", name: "新西兰", dialCode: "+64", flag: "🇳🇿" },
  { code: "IN", name: "印度", dialCode: "+91", flag: "🇮🇳" },
  { code: "BR", name: "巴西", dialCode: "+55", flag: "🇧🇷" },
  { code: "RU", name: "俄罗斯", dialCode: "+7", flag: "🇷🇺" },
  { code: "IT", name: "意大利", dialCode: "+39", flag: "🇮🇹" },
  { code: "ES", name: "西班牙", dialCode: "+34", flag: "🇪🇸" },
  { code: "NL", name: "荷兰", dialCode: "+31", flag: "🇳🇱" },
  { code: "SE", name: "瑞典", dialCode: "+46", flag: "🇸🇪" },
  { code: "NO", name: "挪威", dialCode: "+47", flag: "🇳🇴" },
  { code: "DK", name: "丹麦", dialCode: "+45", flag: "🇩🇰" },
  { code: "FI", name: "芬兰", dialCode: "+358", flag: "🇫🇮" },
  { code: "CH", name: "瑞士", dialCode: "+41", flag: "🇨🇭" },
  { code: "AT", name: "奥地利", dialCode: "+43", flag: "🇦🇹" },
  { code: "BE", name: "比利时", dialCode: "+32", flag: "🇧🇪" },
  { code: "IE", name: "爱尔兰", dialCode: "+353", flag: "🇮🇪" },
  { code: "PT", name: "葡萄牙", dialCode: "+351", flag: "🇵🇹" },
  { code: "GR", name: "希腊", dialCode: "+30", flag: "🇬🇷" },
  { code: "PL", name: "波兰", dialCode: "+48", flag: "🇵🇱" },
  { code: "CZ", name: "捷克", dialCode: "+420", flag: "🇨🇿" },
  { code: "HU", name: "匈牙利", dialCode: "+36", flag: "🇭🇺" },
  { code: "RO", name: "罗马尼亚", dialCode: "+40", flag: "🇷🇴" },
  { code: "BG", name: "保加利亚", dialCode: "+359", flag: "🇧🇬" },
  { code: "HR", name: "克罗地亚", dialCode: "+385", flag: "🇭🇷" },
  { code: "SI", name: "斯洛文尼亚", dialCode: "+386", flag: "🇸🇮" },
  { code: "SK", name: "斯洛伐克", dialCode: "+421", flag: "🇸🇰" },
  { code: "LT", name: "立陶宛", dialCode: "+370", flag: "🇱🇹" },
  { code: "LV", name: "拉脱维亚", dialCode: "+371", flag: "🇱🇻" },
  { code: "EE", name: "爱沙尼亚", dialCode: "+372", flag: "🇪🇪" },
  { code: "MT", name: "马耳他", dialCode: "+356", flag: "🇲🇹" },
  { code: "CY", name: "塞浦路斯", dialCode: "+357", flag: "🇨🇾" },
  { code: "LU", name: "卢森堡", dialCode: "+352", flag: "🇱🇺" },
  { code: "IS", name: "冰岛", dialCode: "+354", flag: "🇮🇸" },
  { code: "MX", name: "墨西哥", dialCode: "+52", flag: "🇲🇽" },
  { code: "AR", name: "阿根廷", dialCode: "+54", flag: "🇦🇷" },
  { code: "CL", name: "智利", dialCode: "+56", flag: "🇨🇱" },
  { code: "CO", name: "哥伦比亚", dialCode: "+57", flag: "🇨🇴" },
  { code: "PE", name: "秘鲁", dialCode: "+51", flag: "🇵🇪" },
  { code: "VE", name: "委内瑞拉", dialCode: "+58", flag: "🇻🇪" },
  { code: "UY", name: "乌拉圭", dialCode: "+598", flag: "🇺🇾" },
  { code: "PY", name: "巴拉圭", dialCode: "+595", flag: "🇵🇾" },
  { code: "BO", name: "玻利维亚", dialCode: "+591", flag: "🇧🇴" },
  { code: "EC", name: "厄瓜多尔", dialCode: "+593", flag: "🇪🇨" },
  { code: "GY", name: "圭亚那", dialCode: "+592", flag: "🇬🇾" },
  { code: "SR", name: "苏里南", dialCode: "+597", flag: "🇸🇷" },
  { code: "ZA", name: "南非", dialCode: "+27", flag: "🇿🇦" },
  { code: "EG", name: "埃及", dialCode: "+20", flag: "🇪🇬" },
  { code: "NG", name: "尼日利亚", dialCode: "+234", flag: "🇳🇬" },
  { code: "KE", name: "肯尼亚", dialCode: "+254", flag: "🇰🇪" },
  { code: "GH", name: "加纳", dialCode: "+233", flag: "🇬🇭" },
  { code: "ET", name: "埃塞俄比亚", dialCode: "+251", flag: "🇪🇹" },
  { code: "TZ", name: "坦桑尼亚", dialCode: "+255", flag: "🇹🇿" },
  { code: "UG", name: "乌干达", dialCode: "+256", flag: "🇺🇬" },
  { code: "DZ", name: "阿尔及利亚", dialCode: "+213", flag: "🇩🇿" },
  { code: "MA", name: "摩洛哥", dialCode: "+212", flag: "🇲🇦" },
  { code: "TN", name: "突尼斯", dialCode: "+216", flag: "🇹🇳" },
  { code: "LY", name: "利比亚", dialCode: "+218", flag: "🇱🇾" },
  { code: "SD", name: "苏丹", dialCode: "+249", flag: "🇸🇩" },
  { code: "SS", name: "南苏丹", dialCode: "+211", flag: "🇸🇸" },
  { code: "CM", name: "喀麦隆", dialCode: "+237", flag: "🇨🇲" },
  { code: "CI", name: "科特迪瓦", dialCode: "+225", flag: "🇨🇮" },
  { code: "SN", name: "塞内加尔", dialCode: "+221", flag: "🇸🇳" },
  { code: "ML", name: "马里", dialCode: "+223", flag: "🇲🇱" },
  { code: "BF", name: "布基纳法索", dialCode: "+226", flag: "🇧🇫" },
  { code: "NE", name: "尼日尔", dialCode: "+227", flag: "🇳🇪" },
  { code: "TD", name: "乍得", dialCode: "+235", flag: "🇹🇩" },
  { code: "CF", name: "中非共和国", dialCode: "+236", flag: "🇨🇫" },
  { code: "CG", name: "刚果共和国", dialCode: "+242", flag: "🇨🇬" },
  { code: "CD", name: "刚果民主共和国", dialCode: "+243", flag: "🇨🇩" },
  { code: "GA", name: "加蓬", dialCode: "+241", flag: "🇬🇦" },
  { code: "GQ", name: "赤道几内亚", dialCode: "+240", flag: "🇬🇶" },
  { code: "ST", name: "圣多美和普林西比", dialCode: "+239", flag: "🇸🇹" },
  { code: "AO", name: "安哥拉", dialCode: "+244", flag: "🇦🇴" },
  { code: "ZM", name: "赞比亚", dialCode: "+260", flag: "🇿🇲" },
  { code: "ZW", name: "津巴布韦", dialCode: "+263", flag: "🇿🇼" },
  { code: "BW", name: "博茨瓦纳", dialCode: "+267", flag: "🇧🇼" },
  { code: "NA", name: "纳米比亚", dialCode: "+264", flag: "🇳🇦" },
  { code: "SZ", name: "斯威士兰", dialCode: "+268", flag: "🇸🇿" },
  { code: "LS", name: "莱索托", dialCode: "+266", flag: "🇱🇸" },
  { code: "MG", name: "马达加斯加", dialCode: "+261", flag: "🇲🇬" },
  { code: "MU", name: "毛里求斯", dialCode: "+230", flag: "🇲🇺" },
  { code: "SC", name: "塞舌尔", dialCode: "+248", flag: "🇸🇨" },
  { code: "KM", name: "科摩罗", dialCode: "+269", flag: "🇰🇲" },
  { code: "DJ", name: "吉布提", dialCode: "+253", flag: "🇩🇯" },
  { code: "SO", name: "索马里", dialCode: "+252", flag: "🇸🇴" },
  { code: "ER", name: "厄立特里亚", dialCode: "+291", flag: "🇪🇷" },
  { code: "RW", name: "卢旺达", dialCode: "+250", flag: "🇷🇼" },
  { code: "BI", name: "布隆迪", dialCode: "+257", flag: "🇧🇮" },
  { code: "MW", name: "马拉维", dialCode: "+265", flag: "🇲🇼" },
  { code: "MZ", name: "莫桑比克", dialCode: "+258", flag: "🇲🇿" },
  { code: "RE", name: "留尼汪", dialCode: "+262", flag: "🇷🇪" },
  { code: "YT", name: "马约特", dialCode: "+262", flag: "🇾🇹" },
  { code: "SH", name: "圣赫勒拿", dialCode: "+290", flag: "🇸🇭" },
  { code: "FK", name: "福克兰群岛", dialCode: "+500", flag: "🇫🇰" },
  { code: "GS", name: "南乔治亚和南桑威奇群岛", dialCode: "+500", flag: "🇬🇸" },
  { code: "IO", name: "英属印度洋领地", dialCode: "+246", flag: "🇮🇴" },
  { code: "TF", name: "法属南部领地", dialCode: "+262", flag: "🇹🇫" },
  { code: "AQ", name: "南极洲", dialCode: "+672", flag: "🇦🇶" },
  { code: "BV", name: "布韦岛", dialCode: "+47", flag: "🇧🇻" },
  { code: "HM", name: "赫德岛和麦克唐纳群岛", dialCode: "+672", flag: "🇭🇲" },
  { code: "NF", name: "诺福克岛", dialCode: "+672", flag: "🇳🇫" },
  { code: "CX", name: "圣诞岛", dialCode: "+61", flag: "🇨🇽" },
  { code: "CC", name: "科科斯群岛", dialCode: "+61", flag: "🇨🇨" },
  { code: "CK", name: "库克群岛", dialCode: "+682", flag: "🇨🇰" },
  { code: "NU", name: "纽埃", dialCode: "+683", flag: "🇳🇺" },
  { code: "TK", name: "托克劳", dialCode: "+690", flag: "🇹🇰" },
  { code: "TO", name: "汤加", dialCode: "+676", flag: "🇹🇴" },
  { code: "WS", name: "萨摩亚", dialCode: "+685", flag: "🇼🇸" },
  { code: "TV", name: "图瓦卢", dialCode: "+688", flag: "🇹🇻" },
  { code: "NR", name: "瑙鲁", dialCode: "+674", flag: "🇳🇷" },
  { code: "KI", name: "基里巴斯", dialCode: "+686", flag: "🇰🇮" },
  { code: "VU", name: "瓦努阿图", dialCode: "+678", flag: "🇻🇺" },
  { code: "NC", name: "新喀里多尼亚", dialCode: "+687", flag: "🇳🇨" },
  { code: "PF", name: "法属波利尼西亚", dialCode: "+689", flag: "🇵🇫" },
  { code: "WF", name: "瓦利斯和富图纳", dialCode: "+681", flag: "🇼🇫" },
  { code: "AS", name: "美属萨摩亚", dialCode: "+1", flag: "🇦🇸" },
  { code: "GU", name: "关岛", dialCode: "+1", flag: "🇬🇺" },
  { code: "MP", name: "北马里亚纳群岛", dialCode: "+1", flag: "🇲🇵" },
  { code: "PW", name: "帕劳", dialCode: "+680", flag: "🇵🇼" },
  { code: "FM", name: "密克罗尼西亚联邦", dialCode: "+691", flag: "🇫🇲" },
  { code: "MH", name: "马绍尔群岛", dialCode: "+692", flag: "🇲🇭" },
  { code: "SB", name: "所罗门群岛", dialCode: "+677", flag: "🇸🇧" },
  { code: "PG", name: "巴布亚新几内亚", dialCode: "+675", flag: "🇵🇬" },
  { code: "FJ", name: "斐济", dialCode: "+679", flag: "🇫🇯" },
  { code: "ID", name: "印度尼西亚", dialCode: "+62", flag: "🇮🇩" },
  { code: "MY", name: "马来西亚", dialCode: "+60", flag: "🇲🇾" },
  { code: "TH", name: "泰国", dialCode: "+66", flag: "🇹🇭" },
  { code: "VN", name: "越南", dialCode: "+84", flag: "🇻🇳" },
  { code: "LA", name: "老挝", dialCode: "+856", flag: "🇱🇦" },
  { code: "KH", name: "柬埔寨", dialCode: "+855", flag: "🇰🇭" },
  { code: "MM", name: "缅甸", dialCode: "+95", flag: "🇲🇲" },
  { code: "BD", name: "孟加拉国", dialCode: "+880", flag: "🇧🇩" },
  { code: "LK", name: "斯里兰卡", dialCode: "+94", flag: "🇱🇰" },
  { code: "MV", name: "马尔代夫", dialCode: "+960", flag: "🇲🇻" },
  { code: "NP", name: "尼泊尔", dialCode: "+977", flag: "🇳🇵" },
  { code: "BT", name: "不丹", dialCode: "+975", flag: "🇧🇹" },
  { code: "PK", name: "巴基斯坦", dialCode: "+92", flag: "🇵🇰" },
  { code: "AF", name: "阿富汗", dialCode: "+93", flag: "🇦🇫" },
  { code: "IR", name: "伊朗", dialCode: "+98", flag: "🇮🇷" },
  { code: "IQ", name: "伊拉克", dialCode: "+964", flag: "🇮🇶" },
  { code: "SY", name: "叙利亚", dialCode: "+963", flag: "🇸🇾" },
  { code: "LB", name: "黎巴嫩", dialCode: "+961", flag: "🇱🇧" },
  { code: "JO", name: "约旦", dialCode: "+962", flag: "🇯🇴" },
  { code: "IL", name: "以色列", dialCode: "+972", flag: "🇮🇱" },
  { code: "PS", name: "巴勒斯坦", dialCode: "+970", flag: "🇵🇸" },
  { code: "SA", name: "沙特阿拉伯", dialCode: "+966", flag: "🇸🇦" },
  { code: "YE", name: "也门", dialCode: "+967", flag: "🇾🇪" },
  { code: "OM", name: "阿曼", dialCode: "+968", flag: "🇴🇲" },
  { code: "AE", name: "阿联酋", dialCode: "+971", flag: "🇦🇪" },
  { code: "QA", name: "卡塔尔", dialCode: "+974", flag: "🇶🇦" },
  { code: "KW", name: "科威特", dialCode: "+965", flag: "🇰🇼" },
  { code: "BH", name: "巴林", dialCode: "+973", flag: "🇧🇭" },
  { code: "TR", name: "土耳其", dialCode: "+90", flag: "🇹🇷" },
  { code: "GE", name: "格鲁吉亚", dialCode: "+995", flag: "🇬🇪" },
  { code: "AM", name: "亚美尼亚", dialCode: "+374", flag: "🇦🇲" },
  { code: "AZ", name: "阿塞拜疆", dialCode: "+994", flag: "🇦🇿" },
  { code: "KZ", name: "哈萨克斯坦", dialCode: "+7", flag: "🇰🇿" },
  { code: "UZ", name: "乌兹别克斯坦", dialCode: "+998", flag: "🇺🇿" },
  { code: "KG", name: "吉尔吉斯斯坦", dialCode: "+996", flag: "🇰🇬" },
  { code: "TJ", name: "塔吉克斯坦", dialCode: "+992", flag: "🇹🇯" },
  { code: "TM", name: "土库曼斯坦", dialCode: "+993", flag: "🇹🇲" },
  { code: "MN", name: "蒙古", dialCode: "+976", flag: "🇲🇳" },
  { code: "KP", name: "朝鲜", dialCode: "+850", flag: "🇰🇵" },
  { code: "PH", name: "菲律宾", dialCode: "+63", flag: "🇵🇭" },
  { code: "BN", name: "文莱", dialCode: "+673", flag: "🇧🇳" },
  { code: "TL", name: "东帝汶", dialCode: "+670", flag: "🇹🇱" },
  { code: "MO", name: "澳门", dialCode: "+853", flag: "🇲🇴" },
]
